// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// AccountCerashopRestrict is the golang structure for table account_cerashop_restrict.
type AccountCerashopRestrict struct {
	MId            uint `orm:"m_id,primary"     json:"m_id"`             //
	IpgNo          uint `orm:"ipg_no,primary"   json:"ipg_no"`           //
	Count          uint `orm:"count"            json:"count"`            //
	NextDate       uint `orm:"next_date"        json:"next_date"`        //
	EndDate        uint `orm:"end_date"         json:"end_date"`         //
	LastAccessDate uint `orm:"last_access_date" json:"last_access_date"` //
}

// Accounts is the golang structure for table accounts.
type Accounts struct {
	UID         int    `orm:"UID,primary" json:"UID"`         //
	Accountname string `orm:"accountname" json:"accountname"` //
	Password    string `orm:"password"    json:"password"`    //
	Qq          string `orm:"qq"          json:"qq"`          //
	Dzuid       int    `orm:"dzuid"       json:"dzuid"`       //
	Billing     int    `orm:"billing"     json:"billing"`     //
	VIP         string `orm:"VIP"         json:"vip"`         //
}

// Accountss is the golang structure for table accountss.
type Accountss struct {
	Uid         int    `orm:"uid,primary" json:"uid"`         //
	Accountname string `orm:"accountname" json:"accountname"` //
	Password    string `orm:"password"    json:"password"`    //
}

// AdminMember is the golang structure for table admin_member.
type AdminMember struct {
	No          int    `orm:"no,primary"   json:"no"`            //
	UserId      string `orm:"user_id"      json:"user_id"`       //
	Password    string `orm:"password"     json:"password"`      //
	Name        string `orm:"name"         json:"name"`          //
	Email       string `orm:"email"        json:"email"`         //
	Phone       string `orm:"phone"        json:"phone"`         //
	Msn         string `orm:"msn"          json:"msn"`           //
	Comment     string `orm:"comment"      json:"comment"`       //
	RegDate     int    `orm:"reg_date"     json:"reg_date"`      //
	Confirm     string `orm:"confirm"      json:"confirm"`       //
	Level       string `orm:"level"        json:"level"`         //
	LevelGroup1 string `orm:"level_group1" json:"level_group_1"` //
	LevelGroup2 string `orm:"level_group2" json:"level_group_2"` //
	LevelGroup3 string `orm:"level_group3" json:"level_group_3"` //
	LevelGroup4 string `orm:"level_group4" json:"level_group_4"` //
	LevelGroup5 string `orm:"level_group5" json:"level_group_5"` //
	LevelGroup6 string `orm:"level_group6" json:"level_group_6"` //
}

// BadUser is the golang structure for table bad_user.
type BadUser struct {
	No        int `orm:"no,primary" json:"no"`         //
	MId       int `orm:"m_id"       json:"m_id"`       //
	BadCode   int `orm:"bad_code"   json:"bad_code"`   //
	CreateDay int `orm:"create_day" json:"create_day"` //
	ExitDay   int `orm:"exit_day"   json:"exit_day"`   //
	AdminN    int `orm:"admin_n"    json:"admin_n"`    //
}

// BakDnfItemInfo is the golang structure for table bak_dnf_item_info.
type BakDnfItemInfo struct {
	ItNo                 uint    `orm:"it_no,primary"           json:"it_no"`                   //
	ItName               string  `orm:"it_name"                 json:"it_name"`                 //
	ItEngName            string  `orm:"it_eng_name"             json:"it_eng_name"`             //
	ItExplain            string  `orm:"it_explain"              json:"it_explain"`              //
	MasterType           uint    `orm:"master_type"             json:"master_type"`             //
	SubType              uint    `orm:"sub_type"                json:"sub_type"`                //
	Job                  string  `orm:"job"                     json:"job"`                     //
	Class                uint    `orm:"class"                   json:"class"`                   //
	Revert               string  `orm:"revert"                  json:"revert"`                  //
	Level                uint    `orm:"level"                   json:"level"`                   //
	Skill                uint    `orm:"skill"                   json:"skill"`                   //
	CreateRatio          float64 `orm:"create_ratio"            json:"create_ratio"`            //
	Rarity               uint    `orm:"rarity"                  json:"rarity"`                  //
	Weight               int     `orm:"weight"                  json:"weight"`                  //
	Price                uint    `orm:"price"                   json:"price"`                   //
	Cash                 uint    `orm:"cash"                    json:"cash"`                    //
	Medal                uint    `orm:"medal"                   json:"medal"`                   //
	Durability           int     `orm:"durability"              json:"durability"`              //
	Cooltime             int     `orm:"cooltime"                json:"cooltime"`                //
	HpMax                int     `orm:"hp_max"                  json:"hp_max"`                  //
	MpMax                int     `orm:"mp_max"                  json:"mp_max"`                  //
	PhyAtt               int     `orm:"phy_att"                 json:"phy_att"`                 //
	PhyDef               int     `orm:"phy_def"                 json:"phy_def"`                 //
	MagAtt               int     `orm:"mag_att"                 json:"mag_att"`                 //
	MagDef               int     `orm:"mag_def"                 json:"mag_def"`                 //
	EquipPhyAtt          int     `orm:"equip_phy_att"           json:"equip_phy_att"`           //
	EquipPhyDef          int     `orm:"equip_phy_def"           json:"equip_phy_def"`           //
	EquipMagAtt          int     `orm:"equip_mag_att"           json:"equip_mag_att"`           //
	EquipMagDef          int     `orm:"equip_mag_def"           json:"equip_mag_def"`           //
	RefFire              int     `orm:"ref_fire"                json:"ref_fire"`                //
	RefWater             int     `orm:"ref_water"               json:"ref_water"`               //
	RefDark              int     `orm:"ref_dark"                json:"ref_dark"`                //
	RefLight             int     `orm:"ref_light"               json:"ref_light"`               //
	RefAll               int     `orm:"ref_all"                 json:"ref_all"`                 //
	RefSlow              int     `orm:"ref_slow"                json:"ref_slow"`                //
	RefFreeze            int     `orm:"ref_freeze"              json:"ref_freeze"`              //
	RefPoison            int     `orm:"ref_poison"              json:"ref_poison"`              //
	RefStun              int     `orm:"ref_stun"                json:"ref_stun"`                //
	RefCus               int     `orm:"ref_cus"                 json:"ref_cus"`                 //
	RefBlind             int     `orm:"ref_blind"               json:"ref_blind"`               //
	RefLite              int     `orm:"ref_lite"                json:"ref_lite"`                //
	RefSton              int     `orm:"ref_ston"                json:"ref_ston"`                //
	RefSleep             int     `orm:"ref_sleep"               json:"ref_sleep"`               //
	RefDeekement         int     `orm:"ref_deekement"           json:"ref_deekement"`           //
	RefDeadlystrike      int     `orm:"ref_deadlystrike"        json:"ref_deadlystrike"`        //
	RefBleeding          int     `orm:"ref_bleeding"            json:"ref_bleeding"`            //
	RefConfuse           int     `orm:"ref_confuse"             json:"ref_confuse"`             //
	RefHold              int     `orm:"ref_hold"                json:"ref_hold"`                //
	RefAllStat           int     `orm:"ref_all_stat"            json:"ref_all_stat"`            //
	RefPierce            int     `orm:"ref_pierce"              json:"ref_pierce"`              //
	RefStuck             int     `orm:"ref_stuck"               json:"ref_stuck"`               //
	InvenMax             int     `orm:"inven_max"               json:"inven_max"`               //
	HpRegenrate          int     `orm:"hp_regenrate"            json:"hp_regenrate"`            //
	MpRegenrate          int     `orm:"mp_regenrate"            json:"mp_regenrate"`            //
	MovSpeed             int     `orm:"mov_speed"               json:"mov_speed"`               //
	AttSpeed             int     `orm:"att_speed"               json:"att_speed"`               //
	Quest                int     `orm:"quest"                   json:"quest"`                   //
	HitRecovery          int     `orm:"hit_recovery"            json:"hit_recovery"`            //
	Jump                 int     `orm:"jump"                    json:"jump"`                    //
	AttElement           string  `orm:"att_element"             json:"att_element"`             //
	AttActiveStatus      int     `orm:"att_active_status"       json:"att_active_status"`       //
	AttActiveStatusRatio float64 `orm:"att_active_status_ratio" json:"att_active_status_ratio"` //
	AttActiveStatusPow   int     `orm:"att_active_status_pow"   json:"att_active_status_pow"`   //
	AttBackforce         int     `orm:"att_backforce"           json:"att_backforce"`           //
	AttUpforce           int     `orm:"att_upforce"             json:"att_upforce"`             //
	AttHpDrain           int     `orm:"att_hp_drain"            json:"att_hp_drain"`            //
	AttMpDrain           int     `orm:"att_mp_drain"            json:"att_mp_drain"`            //
	CriticalhitRate      float64 `orm:"criticalhit_rate"        json:"criticalhit_rate"`        //
	StuckRate            float64 `orm:"stuck_rate"              json:"stuck_rate"`              //
	AttDefenseIgnore     int     `orm:"att_defenseIgnore"       json:"att_defense_ignore"`      //
	SkillLevelup         string  `orm:"skill_levelup"           json:"skill_levelup"`           //
	SetType              string  `orm:"set_type"                json:"set_type"`                //
	Url                  string  `orm:"url"                     json:"url"`                     //
	JewelType            string  `orm:"jewel_type"              json:"jewel_type"`              //
}

// BakMId201304262 is the golang structure for table bak_m_id_20130426_2.
type BakMId201304262 struct {
	MId int `orm:"m_id" json:"m_id"` //
}

// BakMId201304263 is the golang structure for table bak_m_id_20130426_3.
type BakMId201304263 struct {
	UserId  string      `orm:"user_id"  json:"user_id"`  //
	RegDate *gtime.Time `orm:"reg_date" json:"reg_date"` //
}

// ChStatus is the golang structure for table ch_status.
type ChStatus struct {
	GcGroup  uint `orm:"gc_group"  json:"gc_group"`  //
	GcStatus uint `orm:"gc_status" json:"gc_status"` //
}

// CheckPickUpRandomOptionItem is the golang structure for table check_pick_up_random_option_item.
type CheckPickUpRandomOptionItem struct {
	MId        uint `orm:"m_id,primary" json:"m_id"`        //
	CheckCount uint `orm:"check_count"  json:"check_count"` //
}

// DbConnect is the golang structure for table db_connect.
type DbConnect struct {
	No            uint   `orm:"no"              json:"no"`              //
	HostName      string `orm:"host_name"       json:"host_name"`       //
	DbServerGroup uint   `orm:"db_server_group" json:"db_server_group"` //
	DbType        uint   `orm:"db_type"         json:"db_type"`         //
	DbName        string `orm:"db_name"         json:"db_name"`         //
	DbIp          string `orm:"db_ip"           json:"db_ip"`           //
	DbPort        uint   `orm:"db_port"         json:"db_port"`         //
	DbUserid      string `orm:"db_userid"       json:"db_userid"`       //
	DbPasswd      string `orm:"db_passwd"       json:"db_passwd"`       //
	Comments      string `orm:"comments"        json:"comments"`        //
}

// DblabDbConnect130516 is the golang structure for table dblab_db_connect_130516.
type DblabDbConnect130516 struct {
	No            uint   `orm:"no"              json:"no"`              //
	HostName      string `orm:"host_name"       json:"host_name"`       //
	DbServerGroup uint   `orm:"db_server_group" json:"db_server_group"` //
	DbType        uint   `orm:"db_type"         json:"db_type"`         //
	DbName        string `orm:"db_name"         json:"db_name"`         //
	DbIp          string `orm:"db_ip"           json:"db_ip"`           //
	DbPort        uint   `orm:"db_port"         json:"db_port"`         //
	DbUserid      string `orm:"db_userid"       json:"db_userid"`       //
	DbPasswd      string `orm:"db_passwd"       json:"db_passwd"`       //
	Comments      string `orm:"comments"        json:"comments"`        //
}

// DnfCharacMov is the golang structure for table dnf_charac_mov.
type DnfCharacMov struct {
	Id           int `orm:"id,primary"     json:"id"`             //
	MId          int `orm:"m_id"           json:"m_id"`           //
	ServerId     int `orm:"server_id"      json:"server_id"`      //
	CharacNo     int `orm:"charac_no"      json:"charac_no"`      //
	MoveServerId int `orm:"move_server_id" json:"move_server_id"` //
	MoveCharacNo int `orm:"move_charac_no" json:"move_charac_no"` //
	MoveCheck    int `orm:"move_check"     json:"move_check"`     //
}

// DnfEventAddress is the golang structure for table dnf_event_address.
type DnfEventAddress struct {
	EventId int         `orm:"event_id,primary" json:"event_id"` //
	MId     int         `orm:"m_id,primary"     json:"m_id"`     //
	OccDate *gtime.Time `orm:"occ_date"         json:"occ_date"` //
	Zipcode string      `orm:"zipcode"          json:"zipcode"`  //
	Address string      `orm:"address"          json:"address"`  //
	PhoneNo string      `orm:"phone_no"         json:"phone_no"` //
}

// DnfEventEntryNotuse is the golang structure for table dnf_event_entry_notuse.
type DnfEventEntryNotuse struct {
	EventId    int         `orm:"event_id,primary" json:"event_id"`    //
	MId        int         `orm:"m_id,primary"     json:"m_id"`        //
	OccDate    *gtime.Time `orm:"occ_date"         json:"occ_date"`    //
	ServerId   int         `orm:"server_id"        json:"server_id"`   //
	CharacNo   int         `orm:"charac_no"        json:"charac_no"`   //
	ObtainDate *gtime.Time `orm:"obtain_date"      json:"obtain_date"` //
}

// DnfEventInfo is the golang structure for table dnf_event_info.
type DnfEventInfo struct {
	EventId      int         `orm:"event_id,primary"  json:"event_id"`      //
	EventName    string      `orm:"event_name,unique" json:"event_name"`    //
	EventExplain string      `orm:"event_explain"     json:"event_explain"` //
	ApplyType    int         `orm:"apply_type"        json:"apply_type"`    //
	StartDate    *gtime.Time `orm:"start_date"        json:"start_date"`    //
	EndDate      *gtime.Time `orm:"end_date"          json:"end_date"`      //
}

// DnfEventLog is the golang structure for table dnf_event_log.
type DnfEventLog struct {
	LogId      uint   `orm:"log_id,primary" json:"log_id"`      //
	OccTime    int    `orm:"occ_time"       json:"occ_time"`    //
	EventType  uint   `orm:"event_type"     json:"event_type"`  //
	Parameter1 uint   `orm:"parameter1"     json:"parameter_1"` //
	Parameter2 uint   `orm:"parameter2"     json:"parameter_2"` //
	ServerId   uint   `orm:"server_id"      json:"server_id"`   //
	EventFlag  int    `orm:"event_flag"     json:"event_flag"`  //
	StartTime  int    `orm:"start_time"     json:"start_time"`  //
	EndTime    int    `orm:"end_time"       json:"end_time"`    //
	MId        int    `orm:"m_id"           json:"m_id"`        //
	Expl       string `orm:"expl"           json:"expl"`        //
	Etc        string `orm:"etc"            json:"etc"`         //
}

// DnfEventPrize is the golang structure for table dnf_event_prize.
type DnfEventPrize struct {
	PrizeId   int `orm:"prize_id,primary" json:"prize_id"`   //
	MId       int `orm:"m_id,primary"     json:"m_id"`       //
	CheckTime int `orm:"check_time"       json:"check_time"` //
}

// DnfGameMessage is the golang structure for table dnf_game_message.
type DnfGameMessage struct {
	No          uint        `orm:"no,primary"   json:"no"`           //
	Message     string      `orm:"message"      json:"message"`      //
	DisplayType int         `orm:"display_type" json:"display_type"` //
	StartH      uint        `orm:"start_h"      json:"start_h"`      //
	EndH        uint        `orm:"end_h"        json:"end_h"`        //
	OccDate     *gtime.Time `orm:"occ_date"     json:"occ_date"`     //
}

// DnfGameinNotice is the golang structure for table dnf_gamein_notice.
type DnfGameinNotice struct {
	No       int         `orm:"no,primary" json:"no"`        //
	ImgName  string      `orm:"img_name"   json:"img_name"`  //
	ServerId int         `orm:"server_id"  json:"server_id"` //
	RegTime  *gtime.Time `orm:"reg_time"   json:"reg_time"`  //
	OpenFlag string      `orm:"open_flag"  json:"open_flag"` //
}

// DnfMasterCharac is the golang structure for table dnf_master_charac.
type DnfMasterCharac struct {
	MId        int    `orm:"m_id,primary"        json:"m_id"`        //
	GlobalType int    `orm:"global_type,primary" json:"global_type"` //
	ServerId   int    `orm:"server_id,primary"   json:"server_id"`   //
	CharacNo   int    `orm:"charac_no"           json:"charac_no"`   //
	CharacName string `orm:"charac_name"         json:"charac_name"` //
	Job        int    `orm:"job"                 json:"job"`         //
	Lev        int    `orm:"lev"                 json:"lev"`         //
}

// DnfPcroom is the golang structure for table dnf_pcroom.
type DnfPcroom struct {
	IpNo      int    `orm:"ip_no,primary"   json:"ip_no"`     //
	District  string `orm:"district"        json:"district"`  //
	FirmName  string `orm:"firm_name"       json:"firm_name"` //
	Telephone string `orm:"telephone"       json:"telephone"` //
	Address   string `orm:"address"         json:"address"`   //
	Leader    string `orm:"leader"          json:"leader"`    //
	StartIp   string `orm:"start_ip,unique" json:"start_ip"`  //
	EndIp     string `orm:"end_ip,unique"   json:"end_ip"`    //
}

// DnfRestrictInfo is the golang structure for table dnf_restrict_info.
type DnfRestrictInfo struct {
	Category     int         `orm:"category,primary"      json:"category"`      //
	RestrictCode int         `orm:"restrict_code,primary" json:"restrict_code"` //
	RestrictStr  string      `orm:"restrict_str"          json:"restrict_str"`  //
	RegDate      *gtime.Time `orm:"reg_date"              json:"reg_date"`      //
}

// DnfRestrictState is the golang structure for table dnf_restrict_state.
type DnfRestrictState struct {
	ServerGroup   int         `orm:"server_group,primary"  json:"server_group"`   //
	Category      int         `orm:"category,primary"      json:"category"`       //
	RestrictCode  int         `orm:"restrict_code,primary" json:"restrict_code"`  //
	RestrictValue string      `orm:"restrict_value"        json:"restrict_value"` //
	ModDate       *gtime.Time `orm:"mod_date"              json:"mod_date"`       //
	RegDate       *gtime.Time `orm:"reg_date"              json:"reg_date"`       //
}

// DnfStory is the golang structure for table dnf_story.
type DnfStory struct {
	No          int         `orm:"no,primary"   json:"no"`           //
	StoryType   int         `orm:"story_type"   json:"story_type"`   //
	NoticeFlag  int         `orm:"notice_flag"  json:"notice_flag"`  //
	MId         int         `orm:"m_id"         json:"m_id"`         //
	RegId       string      `orm:"reg_id"       json:"reg_id"`       //
	Title       string      `orm:"title"        json:"title"`        //
	Url         string      `orm:"url"          json:"url"`          //
	ImgName     string      `orm:"img_name"     json:"img_name"`     //
	Opt         uint        `orm:"opt"          json:"opt"`          //
	OpenFlag    string      `orm:"open_flag"    json:"open_flag"`    //
	RegDate     *gtime.Time `orm:"reg_date"     json:"reg_date"`     //
	Hits        uint        `orm:"hits"         json:"hits"`         //
	ReserveTime uint        `orm:"reserve_time" json:"reserve_time"` //
	Content     string      `orm:"content"      json:"content"`      //
}

// DnfTestrMId is the golang structure for table dnf_testr_m_id.
type DnfTestrMId struct {
	MId int `orm:"m_id,primary" json:"m_id"` //
	Sex int `orm:"sex"          json:"sex"`  //
}

// EventAradBirthday6Th is the golang structure for table event_arad_birthday_6th.
type EventAradBirthday6Th struct {
	Server uint `orm:"server,primary" json:"server"` //
	Point  uint `orm:"point"          json:"point"`  //
}

// EventAradlotto0809Entry is the golang structure for table event_aradlotto_0809_entry.
type EventAradlotto0809Entry struct {
	MId      int    `orm:"m_id,primary" json:"m_id"`      //
	OccDate  int    `orm:"occ_date"     json:"occ_date"`  //
	LottoNum string `orm:"lotto_num"    json:"lotto_num"` //
}

// EventCharacMov1Th is the golang structure for table event_charac_mov_1th.
type EventCharacMov1Th struct {
	Id           int `orm:"id,primary"     json:"id"`             //
	MId          int `orm:"m_id"           json:"m_id"`           //
	ServerId     int `orm:"server_id"      json:"server_id"`      //
	CharacNo     int `orm:"charac_no"      json:"charac_no"`      //
	MoveServerId int `orm:"move_server_id" json:"move_server_id"` //
	MoveCharacNo int `orm:"move_charac_no" json:"move_charac_no"` //
	MoveCheck    int `orm:"move_check"     json:"move_check"`     //
}

// EventCharacMov1ThEntry is the golang structure for table event_charac_mov_1th_entry.
type EventCharacMov1ThEntry struct {
	MId       int `orm:"m_id,primary" json:"m_id"`       //
	OccTime   int `orm:"occ_time"     json:"occ_time"`   //
	ItNo      int `orm:"it_no"        json:"it_no"`      //
	ItemCheck int `orm:"item_check"   json:"item_check"` //
}

// EventGoldcardCnt is the golang structure for table event_goldcard_cnt.
type EventGoldcardCnt struct {
	ItemNo  int         `orm:"item_no,primary"  json:"item_no"`  //
	OccDate *gtime.Time `orm:"occ_date,primary" json:"occ_date"` //
	Cnt     int         `orm:"cnt"              json:"cnt"`      //
}

// EventGoldcardEntry1 is the golang structure for table event_goldcard_entry1.
type EventGoldcardEntry1 struct {
	OccDate int `orm:"occ_date,primary" json:"occ_date"` //
	MId     int `orm:"m_id,primary"     json:"m_id"`     //
	ItemNo  int `orm:"item_no"          json:"item_no"`  //
}

// EventGoldcardEntry2 is the golang structure for table event_goldcard_entry2.
type EventGoldcardEntry2 struct {
	OccDate   int  `orm:"occ_date,primary" json:"occ_date"`   //
	MId       int  `orm:"m_id,primary"     json:"m_id"`       //
	ServerId  int  `orm:"server_id"        json:"server_id"`  //
	CharacNo  int  `orm:"charac_no"        json:"charac_no"`  //
	ItemNo    uint `orm:"item_no"          json:"item_no"`    //
	ItemCheck int  `orm:"item_check"       json:"item_check"` //
}

// EventGoldcardInfo is the golang structure for table event_goldcard_info.
type EventGoldcardInfo struct {
	MId    int  `orm:"m_id,primary" json:"m_id"`   //
	Coupon uint `orm:"coupon"       json:"coupon"` //
}

// EventHinamatsuriCnt is the golang structure for table event_hinamatsuri_cnt.
type EventHinamatsuriCnt struct {
	Cnt int `orm:"cnt" json:"cnt"` //
}

// EventMage2Years is the golang structure for table event_mage_2years.
type EventMage2Years struct {
	MId        int         `orm:"m_id,primary"        json:"m_id"`        //
	ServerInfo uint        `orm:"server_info,primary" json:"server_info"` //
	CharacNo   int         `orm:"charac_no,primary"   json:"charac_no"`   //
	CharacName string      `orm:"charac_name"         json:"charac_name"` //
	CreateTime *gtime.Time `orm:"create_time"         json:"create_time"` //
	DeleteTime *gtime.Time `orm:"delete_time"         json:"delete_time"` //
	DeleteFlag int         `orm:"delete_flag"         json:"delete_flag"` //
}

// EventNewmember0709Entry is the golang structure for table event_newmember0709_entry.
type EventNewmember0709Entry struct {
	MId        int  `orm:"m_id,primary" json:"m_id"`         //
	OccDate    uint `orm:"occ_date"     json:"occ_date"`     //
	ServerId   int  `orm:"server_id"    json:"server_id"`    //
	CharacNo   int  `orm:"charac_no"    json:"charac_no"`    //
	Item1No    uint `orm:"item1_no"     json:"item_1_no"`    //
	Item1Check uint `orm:"item1_check"  json:"item_1_check"` //
	Item2No    uint `orm:"item2_no"     json:"item_2_no"`    //
	Item2Check uint `orm:"item2_check"  json:"item_2_check"` //
}

// EventPandoraEntry200905 is the golang structure for table event_pandora_entry_200905.
type EventPandoraEntry200905 struct {
	MId      uint        `orm:"m_id,primary"      json:"m_id"`      //
	OccDate  *gtime.Time `orm:"occ_date,primary"  json:"occ_date"`  //
	ServerId uint        `orm:"server_id,primary" json:"server_id"` //
	CharacNo uint        `orm:"charac_no"         json:"charac_no"` //
}

// EventQuestPartyMemberWeb is the golang structure for table event_quest_party_member_web.
type EventQuestPartyMemberWeb struct {
	MId          int         `orm:"m_id,primary"      json:"m_id"`           //
	ServerId     int         `orm:"server_id,primary" json:"server_id"`      //
	CharacNo     int         `orm:"charac_no,primary" json:"charac_no"`      //
	QuestNo      int         `orm:"quest_no,primary"  json:"quest_no"`       //
	OccTime      *gtime.Time `orm:"occ_time"          json:"occ_time"`       //
	SendCharacNo int         `orm:"send_charac_no"    json:"send_charac_no"` //
}

// EventQuizquizStamp is the golang structure for table event_quizquiz_stamp.
type EventQuizquizStamp struct {
	MId     int         `orm:"m_id,primary"   json:"m_id"`     //
	Degree  int         `orm:"degree,primary" json:"degree"`   //
	Stamp   int         `orm:"stamp"          json:"stamp"`    //
	OccTime *gtime.Time `orm:"occ_time"       json:"occ_time"` //
}

// EventSkill2025Entry is the golang structure for table event_skill2025_entry.
type EventSkill2025Entry struct {
	MId      int         `orm:"m_id,primary" json:"m_id"`      //
	ServerId int         `orm:"server_id"    json:"server_id"` //
	CharacNo int         `orm:"charac_no"    json:"charac_no"` //
	OccTime  *gtime.Time `orm:"occ_time"     json:"occ_time"`  //
}

// EventTowerEntry is the golang structure for table event_tower_entry.
type EventTowerEntry struct {
	MId        int  `orm:"m_id,primary" json:"m_id"`         //
	OccDate    uint `orm:"occ_date"     json:"occ_date"`     //
	OccCheck   uint `orm:"occ_check"    json:"occ_check"`    //
	ServerId   int  `orm:"server_id"    json:"server_id"`    //
	CharacNo   int  `orm:"charac_no"    json:"charac_no"`    //
	Item1No    uint `orm:"item1_no"     json:"item_1_no"`    //
	Item1Check uint `orm:"item1_check"  json:"item_1_check"` //
	Item2No    uint `orm:"item2_no"     json:"item_2_no"`    //
	Item2Check uint `orm:"item2_check"  json:"item_2_check"` //
	Item3No    uint `orm:"item3_no"     json:"item_3_no"`    //
	Item3Check uint `orm:"item3_check"  json:"item_3_check"` //
}

// EventWebmoneystampEntry is the golang structure for table event_webmoneystamp_entry.
type EventWebmoneystampEntry struct {
	MId            int         `orm:"m_id,primary"     json:"m_id"`             //
	OccTime        *gtime.Time `orm:"occ_time"         json:"occ_time"`         //
	AttendPoint    uint        `orm:"attend_point"     json:"attend_point"`     //
	LastAttendTime *gtime.Time `orm:"last_attend_time" json:"last_attend_time"` //
	ReturnFlag     int         `orm:"return_flag"      json:"return_flag"`      //
	EntryItem      int         `orm:"entry_item"       json:"entry_item"`       //
}

// EventWebmoneystampItem is the golang structure for table event_webmoneystamp_item.
type EventWebmoneystampItem struct {
	MId       int  `orm:"m_id,primary"     json:"m_id"`       //
	OccTime   int  `orm:"occ_time,primary" json:"occ_time"`   //
	ServerId  int  `orm:"server_id"        json:"server_id"`  //
	CharacNo  int  `orm:"charac_no"        json:"charac_no"`  //
	ItemNo    uint `orm:"item_no"          json:"item_no"`    //
	ItemCheck uint `orm:"item_check"       json:"item_check"` //
}

// GameChannel is the golang structure for table game_channel.
type GameChannel struct {
	GcNo          uint   `orm:"gc_no,primary"  json:"gc_no"`          //
	GcNow         uint   `orm:"gc_now"         json:"gc_now"`         //
	GcIp          string `orm:"gc_ip"          json:"gc_ip"`          //
	GcPort        uint   `orm:"gc_port"        json:"gc_port"`        //
	GcMax         uint   `orm:"gc_max"         json:"gc_max"`         //
	GcGame        uint   `orm:"gc_game"        json:"gc_game"`        //
	GcChannel     string `orm:"gc_channel"     json:"gc_channel"`     //
	GcChGroup     int    `orm:"gc_ch_group"    json:"gc_ch_group"`    //
	GcChanneltype string `orm:"gc_channeltype" json:"gc_channeltype"` //
}

// GeoAllow is the golang structure for table geo_allow.
type GeoAllow struct {
	AllowIp    string      `orm:"allow_ip,primary" json:"allow_ip"`     //
	AllowCCode string      `orm:"allow_c_code"     json:"allow_c_code"` //
	AllowDate  *gtime.Time `orm:"allow_date"       json:"allow_date"`   //
}

// GeoAllowCountry is the golang structure for table geo_allow_country.
type GeoAllowCountry struct {
	ServerGroup int         `orm:"server_group,primary" json:"server_group"` //
	CountryCode string      `orm:"country_code,primary" json:"country_code"` //
	RegDate     *gtime.Time `orm:"reg_date"             json:"reg_date"`     //
}

// GeoCountryCode is the golang structure for table geo_country_code.
type GeoCountryCode struct {
	CodeNo        int    `orm:"code_no,primary"        json:"code_no"`          //
	CountryCodeA2 string `orm:"country_code_a2,unique" json:"country_code_a_2"` //
	CountryCodeA3 string `orm:"country_code_a3,unique" json:"country_code_a_3"` //
	Country       string `orm:"country"                json:"country"`          //
}

// GeoReject is the golang structure for table geo_reject.
type GeoReject struct {
	RejIp       string      `orm:"rej_ip,primary" json:"rej_ip"`        //
	RejCCode    string      `orm:"rej_c_code"     json:"rej_c_code"`    //
	RejIpCount  uint        `orm:"rej_ip_count"   json:"rej_ip_count"`  //
	RejLastDate *gtime.Time `orm:"rej_last_date"  json:"rej_last_date"` //
	RejChk      string      `orm:"rej_chk"        json:"rej_chk"`       //
	RejSrc      string      `orm:"rej_src"        json:"rej_src"`       //
}

// GiftTicketEntry is the golang structure for table gift_ticket_entry.
type GiftTicketEntry struct {
	Id         uint   `orm:"id,primary"  json:"id"`          //
	GiftNo     uint   `orm:"gift_no"     json:"gift_no"`     //
	BuyerId    uint   `orm:"buyer_id"    json:"buyer_id"`    //
	BuyerDate  uint   `orm:"buyer_date"  json:"buyer_date"`  //
	BuyerCode  string `orm:"buyer_code"  json:"buyer_code"`  //
	BuyerCheck uint   `orm:"buyer_check" json:"buyer_check"` //
	OtherId    uint   `orm:"other_id"    json:"other_id"`    //
	OtherDate  uint   `orm:"other_date"  json:"other_date"`  //
	OtherCode  string `orm:"other_code"  json:"other_code"`  //
	OtherCheck uint   `orm:"other_check" json:"other_check"` //
	Message    string `orm:"message"     json:"message"`     //
}

// GmManifestNotuse is the golang structure for table gm_manifest_notuse.
type GmManifestNotuse struct {
	MId   int  `orm:"m_id,primary" json:"m_id"`  //
	Level uint `orm:"level"        json:"level"` //
}

// GuildBbs is the golang structure for table guild_bbs.
type GuildBbs struct {
	Gno      int    `orm:"gno,primary" json:"gno"`       //
	BdId     int    `orm:"bd_id"       json:"bd_id"`     //
	Empyn    int    `orm:"empyn"       json:"empyn"`     //
	Mgno     int    `orm:"mgno"        json:"mgno"`      //
	Open     int    `orm:"open"        json:"open"`      //
	Main     int    `orm:"main"        json:"main"`      //
	RegDate  int    `orm:"reg_date"    json:"reg_date"`  //
	ModDate  int    `orm:"mod_date"    json:"mod_date"`  //
	Hits     uint   `orm:"hits"        json:"hits"`      //
	BodyType string `orm:"body_type"   json:"body_type"` //
	MId      int    `orm:"m_id"        json:"m_id"`      //
	RegId    string `orm:"reg_id"      json:"reg_id"`    //
	Subject  string `orm:"subject"     json:"subject"`   //
}

// GuildBody is the golang structure for table guild_body.
type GuildBody struct {
	Gno  int    `orm:"gno,primary" json:"gno"`  //
	Body string `orm:"body"        json:"body"` //
}

// GuildEvent is the golang structure for table guild_event.
type GuildEvent struct {
	Gno     int         `orm:"gno,primary" json:"gno"`      //
	SttDate *gtime.Time `orm:"stt_date"    json:"stt_date"` //
	EndDate *gtime.Time `orm:"end_date"    json:"end_date"` //
	AnnDate *gtime.Time `orm:"ann_date"    json:"ann_date"` //
	PageUrl string      `orm:"page_url"    json:"page_url"` //
}

// GuildFiles is the golang structure for table guild_files.
type GuildFiles struct {
	Gno          int    `orm:"gno,primary"   json:"gno"`           //
	GfNo         int    `orm:"gf_no,primary" json:"gf_no"`         //
	FileServer   string `orm:"file_server"   json:"file_server"`   //
	FileLocation string `orm:"file_location" json:"file_location"` //
}

// GuildHalloffame is the golang structure for table guild_halloffame.
type GuildHalloffame struct {
	FameId    int    `orm:"fame_id,primary"   json:"fame_id"`    //
	ServerId  int    `orm:"server_id,primary" json:"server_id"`  //
	GuildId   int    `orm:"guild_id"          json:"guild_id"`   //
	GuildName string `orm:"guild_name"        json:"guild_name"` //
	FileUrl   string `orm:"file_url"          json:"file_url"`   //
	OpenFlag  int    `orm:"open_flag"         json:"open_flag"`  //
	MainFlag  int    `orm:"main_flag"         json:"main_flag"`  //
}

// GuildHalloffameHtml is the golang structure for table guild_halloffame_html.
type GuildHalloffameHtml struct {
	FameId int    `orm:"fame_id,primary" json:"fame_id"` //
	Title  string `orm:"title"           json:"title"`   //
	Html   string `orm:"html"            json:"html"`    //
}

// GuildInfo is the golang structure for table guild_info.
type GuildInfo struct {
	GuildId          int         `orm:"guild_id,primary"   json:"guild_id"`           //
	ServerId         int         `orm:"server_id"          json:"server_id"`          //
	GuildName        string      `orm:"guild_name"         json:"guild_name"`         //
	MasterId         int         `orm:"master_id"          json:"master_id"`          //
	MasterNo         int         `orm:"master_no"          json:"master_no"`          //
	MasterName       string      `orm:"master_name"        json:"master_name"`        //
	GuildUrl         string      `orm:"guild_url"          json:"guild_url"`          //
	GuildIcon        uint        `orm:"guild_icon"         json:"guild_icon"`         //
	CreateTime       *gtime.Time `orm:"create_time"        json:"create_time"`        //
	Lev              int         `orm:"lev"                json:"lev"`                //
	Ability          int         `orm:"ability"            json:"ability"`            //
	ExpireFlag       int         `orm:"expire_flag"        json:"expire_flag"`        //
	ExpireTime       *gtime.Time `orm:"expire_time"        json:"expire_time"`        //
	MemberSecedeTime *gtime.Time `orm:"member_secede_time" json:"member_secede_time"` //
	MemberCount      int         `orm:"member_count"       json:"member_count"`       //
	RecommendFlag    int         `orm:"recommend_flag"     json:"recommend_flag"`     //
	RecommendTime    *gtime.Time `orm:"recommend_time"     json:"recommend_time"`     //
	GuildPoint       uint        `orm:"guild_point"        json:"guild_point"`        //
	GuildPointAcc    uint        `orm:"guild_point_acc"    json:"guild_point_acc"`    //
	GuildPointPrev   uint        `orm:"guild_point_prev"   json:"guild_point_prev"`   //
	GuildRank        uint        `orm:"guild_rank"         json:"guild_rank"`         //
	GuildWarPoint    uint        `orm:"guild_war_point"    json:"guild_war_point"`    //
	FinalEntry       uint        `orm:"final_entry"        json:"final_entry"`        //
	FinalWin         uint        `orm:"final_win"          json:"final_win"`          //
	GuildIconAuth    int         `orm:"guild_icon_auth"    json:"guild_icon_auth"`    //
	GuildExp         uint        `orm:"guild_exp"          json:"guild_exp"`          //
}

// GuildIntroduce is the golang structure for table guild_introduce.
type GuildIntroduce struct {
	GuildId   int    `orm:"guild_id,primary" json:"guild_id"`  //
	ServerId  int    `orm:"server_id"        json:"server_id"` //
	Introduce string `orm:"introduce"        json:"introduce"` //
}

// GuildMember is the golang structure for table guild_member.
type GuildMember struct {
	GuildId         int         `orm:"guild_id,primary"  json:"guild_id"`          //
	MId             int         `orm:"m_id"              json:"m_id"`              //
	ServerId        int         `orm:"server_id"         json:"server_id"`         //
	CharacNo        int         `orm:"charac_no,primary" json:"charac_no"`         //
	CharacName      string      `orm:"charac_name"       json:"charac_name"`       //
	NickName        string      `orm:"nick_name"         json:"nick_name"`         //
	Grade           int         `orm:"grade"             json:"grade"`             //
	Job             int         `orm:"job"               json:"job"`               //
	GrowType        int         `orm:"grow_type"         json:"grow_type"`         //
	Lev             int         `orm:"lev"               json:"lev"`               //
	Age             int         `orm:"age"               json:"age"`               //
	BornYear        string      `orm:"born_year"         json:"born_year"`         //
	Sex             string      `orm:"sex"               json:"sex"`               //
	ApplyTime       *gtime.Time `orm:"apply_time"        json:"apply_time"`        //
	MemberTime      *gtime.Time `orm:"member_time"       json:"member_time"`       //
	MemberFlag      int         `orm:"member_flag"       json:"member_flag"`       //
	BbsCnt          uint        `orm:"bbs_cnt"           json:"bbs_cnt"`           //
	LastVisitTime   *gtime.Time `orm:"last_visit_time"   json:"last_visit_time"`   //
	SecedeType      int         `orm:"secede_type"       json:"secede_type"`       //
	SecedeTime      *gtime.Time `orm:"secede_time"       json:"secede_time"`       //
	MemberPoint     uint        `orm:"member_point"      json:"member_point"`      //
	MemberPointPrev uint        `orm:"member_point_prev" json:"member_point_prev"` //
	LastPlayTime    *gtime.Time `orm:"last_play_time"    json:"last_play_time"`    //
}

// GuildMemberIntroduce is the golang structure for table guild_member_introduce.
type GuildMemberIntroduce struct {
	GuildId   int    `orm:"guild_id,primary"  json:"guild_id"`  //
	CharacNo  int    `orm:"charac_no,primary" json:"charac_no"` //
	Introduce string `orm:"introduce"         json:"introduce"` //
}

// GuildRank is the golang structure for table guild_rank.
type GuildRank struct {
	ServerId       int    `orm:"server_id,primary" json:"server_id"`        //
	GuildId        int    `orm:"guild_id,primary"  json:"guild_id"`         //
	GuildName      string `orm:"guild_name"        json:"guild_name"`       //
	GuildRank      uint   `orm:"guild_Rank"        json:"guild_rank"`       //
	GuildPoint     uint   `orm:"guild_point"       json:"guild_point"`      //
	GuildAccPoint  uint   `orm:"guild_acc_point"   json:"guild_acc_point"`  //
	GuildVisit     uint   `orm:"guild_visit"       json:"guild_visit"`      //
	GuildAccVisit  uint   `orm:"guild_acc_visit"   json:"guild_acc_visit"`  //
	GuildMember    uint   `orm:"guild_member"      json:"guild_member"`     //
	GuildAccMember uint   `orm:"guild_acc_member"  json:"guild_acc_member"` //
	GuildAvgLev    uint   `orm:"guild_avg_lev"     json:"guild_avg_lev"`    //
}

// GuildRecommend is the golang structure for table guild_recommend.
type GuildRecommend struct {
	No            int         `orm:"no,primary"     json:"no"`             //
	GuildId       int         `orm:"guild_id"       json:"guild_id"`       //
	ServerId      int         `orm:"server_id"      json:"server_id"`      //
	CharacNo      int         `orm:"charac_no"      json:"charac_no"`      //
	CharacName    string      `orm:"charac_name"    json:"charac_name"`    //
	Comment       string      `orm:"comment"        json:"comment"`        //
	RecommendTime *gtime.Time `orm:"recommend_time" json:"recommend_time"` //
}

// GuildStat is the golang structure for table guild_stat.
type GuildStat struct {
	OccDate      *gtime.Time `orm:"occ_date,primary"  json:"occ_date"`       //
	Lev          uint        `orm:"lev,primary"       json:"lev"`            //
	ServerId     int         `orm:"server_id,primary" json:"server_id"`      //
	CreateNo     int         `orm:"create_no"         json:"create_no"`      //
	AccCreateNo  int         `orm:"acc_create_no"     json:"acc_create_no"`  //
	MemberNo     int         `orm:"member_no"         json:"member_no"`      //
	AccMemberNo  int         `orm:"acc_member_no"     json:"acc_member_no"`  //
	AvgLev       float64     `orm:"avg_lev"           json:"avg_lev"`        //
	AvgMasterLev float64     `orm:"avg_master_lev"    json:"avg_master_lev"` //
}

// GuildStatMonth is the golang structure for table guild_stat_month.
type GuildStatMonth struct {
	OccDate          *gtime.Time `orm:"occ_date,primary"    json:"occ_date"`            //
	Lev              uint        `orm:"lev,primary"         json:"lev"`                 //
	ServerId         int         `orm:"server_id,primary"   json:"server_id"`           //
	AvgGuildPoint    int         `orm:"avg_guild_point"     json:"avg_guild_point"`     //
	AvgGuildPointAcc int         `orm:"avg_guild_point_acc" json:"avg_guild_point_acc"` //
}

// GuildVisit is the golang structure for table guild_visit.
type GuildVisit struct {
	GuildId    int `orm:"guild_id,primary" json:"guild_id"`    //
	ServerId   int `orm:"server_id"        json:"server_id"`   //
	TotalVisit int `orm:"total_visit"      json:"total_visit"` //
	TodayVisit int `orm:"today_visit"      json:"today_visit"` //
}

// LimitCreateCharacter is the golang structure for table limit_create_character.
type LimitCreateCharacter struct {
	MId            uint        `orm:"m_id,primary"     json:"m_id"`             //
	Count          uint        `orm:"count"            json:"count"`            //
	LastAccessTime *gtime.Time `orm:"last_access_time" json:"last_access_time"` //
}

// LimitCreateCharacterIp is the golang structure for table limit_create_character_ip.
type LimitCreateCharacterIp struct {
	Ip             uint        `orm:"ip,primary"       json:"ip"`               //
	IpStr          string      `orm:"ip_str"           json:"ip_str"`           //
	LastAccessTime *gtime.Time `orm:"last_access_time" json:"last_access_time"` //
	Count          uint        `orm:"count"            json:"count"`            //
	LastAccessMid  uint        `orm:"last_access_mid"  json:"last_access_mid"`  //
}

// LimitedShopManager is the golang structure for table limited_shop_manager.
type LimitedShopManager struct {
	No                     uint   `orm:"no,primary"                 json:"no"`                         //
	OccTime                uint   `orm:"occ_time"                   json:"occ_time"`                   //
	ServerId               uint   `orm:"server_id,primary"          json:"server_id"`                  //
	IpgNo                  uint   `orm:"ipg_no,primary"             json:"ipg_no"`                     //
	ItemNo                 uint   `orm:"item_no"                    json:"item_no"`                    //
	ItemCnt                uint   `orm:"item_cnt"                   json:"item_cnt"`                   //
	CeraPrice              uint   `orm:"cera_price"                 json:"cera_price"`                 //
	GoldPrice              uint   `orm:"gold_price"                 json:"gold_price"`                 //
	AvatarPeriodType       int    `orm:"avatar_period_type"         json:"avatar_period_type"`         //
	TotalCnt               int    `orm:"total_cnt"                  json:"total_cnt"`                  //
	SellCnt                uint   `orm:"sell_cnt"                   json:"sell_cnt"`                   //
	RestrictNo             uint   `orm:"restrict_no"                json:"restrict_no"`                //
	StartTime              uint   `orm:"start_time"                 json:"start_time"`                 //
	EndTime                uint   `orm:"end_time"                   json:"end_time"`                   //
	RealEndTime            uint   `orm:"real_end_time"              json:"real_end_time"`              //
	NpcIdx                 uint   `orm:"npc_idx"                    json:"npc_idx"`                    //
	CondCharacJob          uint   `orm:"cond_charac_job"            json:"cond_charac_job"`            //
	CondLevBegin           uint   `orm:"cond_lev_begin"             json:"cond_lev_begin"`             //
	CondLevEnd             uint   `orm:"cond_lev_end"               json:"cond_lev_end"`               //
	CondAccCreateTimeBegin uint   `orm:"cond_acc_create_time_begin" json:"cond_acc_create_time_begin"` //
	CondAccCreateTimeEnd   uint   `orm:"cond_acc_create_time_end"   json:"cond_acc_create_time_end"`   //
	CondChaCreateTimeBegin uint   `orm:"cond_cha_create_time_begin" json:"cond_cha_create_time_begin"` //
	CondChaCreateTimeEnd   uint   `orm:"cond_cha_create_time_end"   json:"cond_cha_create_time_end"`   //
	StatusFlag             uint   `orm:"status_flag"                json:"status_flag"`                //
	Title                  string `orm:"title"                      json:"title"`                      //
	RangeSection           uint   `orm:"range_section"              json:"range_section"`              //
	ReasonEtc              string `orm:"reason_etc"                 json:"reason_etc"`                 //
	ReasonStop             string `orm:"reason_stop"                json:"reason_stop"`                //
	PosFlag                string `orm:"pos_flag"                   json:"pos_flag"`                   //
}

// LogQueryStat is the golang structure for table log_query_stat.
type LogQueryStat struct {
	OccTime      *gtime.Time `orm:"occ_time,primary" json:"occ_time"`      //
	QId          uint        `orm:"q_id,primary"     json:"q_id"`          //
	GcNo         uint        `orm:"gc_no,primary"    json:"gc_no"`         //
	Total        uint        `orm:"total"            json:"total"`         //
	ResponseTime uint        `orm:"response_time"    json:"response_time"` //
}

// MWithdraw is the golang structure for table m_withdraw.
type MWithdraw struct {
	MId       int         `orm:"m_id,primary" json:"m_id"`       //
	UserId    string      `orm:"user_id"      json:"user_id"`    //
	UserName  string      `orm:"user_name"    json:"user_name"`  //
	FirstSsn  string      `orm:"first_ssn"    json:"first_ssn"`  //
	SecondSsn string      `orm:"second_ssn"   json:"second_ssn"` //
	Passwd    string      `orm:"passwd"       json:"passwd"`     //
	MobileNo  string      `orm:"mobile_no"    json:"mobile_no"`  //
	RegDate   int         `orm:"reg_date"     json:"reg_date"`   //
	Email     string      `orm:"email"        json:"email"`      //
	QNo       int         `orm:"q_no"         json:"q_no"`       //
	QAnswer   string      `orm:"q_answer"     json:"q_answer"`   //
	UpdtDate  *gtime.Time `orm:"updt_date"    json:"updt_date"`  //
	State     int         `orm:"state"        json:"state"`      //
	WType     int         `orm:"w_type"       json:"w_type"`     //
	WCause    string      `orm:"w_cause"      json:"w_cause"`    //
	WDate     int         `orm:"w_date"       json:"w_date"`     //
	Nickname  string      `orm:"nickname"     json:"nickname"`   //
}

// MaxCount is the golang structure for table max_count.
type MaxCount struct {
	ServerInfo uint        `orm:"server_info" json:"server_info"` //
	McMax      uint        `orm:"mc_max"      json:"mc_max"`      //
	McDate     *gtime.Time `orm:"mc_date"     json:"mc_date"`     //
}

// MaxCountChannel is the golang structure for table max_count_channel.
type MaxCountChannel struct {
	ServerInfo    uint        `orm:"server_info"    json:"server_info"`    //
	GcChanneltype string      `orm:"gc_channeltype" json:"gc_channeltype"` //
	McMax         uint        `orm:"mc_max"         json:"mc_max"`         //
	McDate        *gtime.Time `orm:"mc_date"        json:"mc_date"`        //
}

// MaxCountPvp is the golang structure for table max_count_pvp.
type MaxCountPvp struct {
	ServerInfo uint        `orm:"server_info" json:"server_info"` //
	McMax      uint        `orm:"mc_max"      json:"mc_max"`      //
	McDate     *gtime.Time `orm:"mc_date"     json:"mc_date"`     //
}

// MaxCountV2 is the golang structure for table max_count_v2.
type MaxCountV2 struct {
	ServerInfo               uint        `orm:"server_info"                json:"server_info"`                //
	NumOccupationsCharscreen uint        `orm:"num_occupations_charscreen" json:"num_occupations_charscreen"` //
	NumOccupationsSeriaroom  uint        `orm:"num_occupations_seriaroom"  json:"num_occupations_seriaroom"`  //
	NumLoginPerMin           uint        `orm:"num_login_per_min"          json:"num_login_per_min"`          //
	NumLogoutPerMin          uint        `orm:"num_logout_per_min"         json:"num_logout_per_min"`         //
	McDate                   *gtime.Time `orm:"mc_date"                    json:"mc_date"`                    //
}

// MemberAbnomal is the golang structure for table member_abnomal.
type MemberAbnomal struct {
	UserId       string `orm:"user_id,primary" json:"user_id"`       //
	OverlabCount int    `orm:"overlab_count"   json:"overlab_count"` //
}

// MemberBroadcast is the golang structure for table member_broadcast.
type MemberBroadcast struct {
	EventId    int         `orm:"event_id,primary"   json:"event_id"`    //
	MId        int         `orm:"m_id,primary"       json:"m_id"`        //
	ServerId   int         `orm:"server_id,primary"  json:"server_id"`   //
	CharacNo   int         `orm:"charac_no,primary"  json:"charac_no"`   //
	CharacName string      `orm:"charac_name,unique" json:"charac_name"` //
	StartTime  *gtime.Time `orm:"start_time,primary" json:"start_time"`  //
	EndTime    *gtime.Time `orm:"end_time"           json:"end_time"`    //
}

// MemberCaptchaInfo is the golang structure for table member_captcha_info.
type MemberCaptchaInfo struct {
	MId       uint `orm:"m_id,primary" json:"m_id"`       //
	CertTime  uint `orm:"cert_time"    json:"cert_time"`  //
	FailCount uint `orm:"fail_count"   json:"fail_count"` //
}

// MemberHandicap is the golang structure for table member_handicap.
type MemberHandicap struct {
	EventId       int         `orm:"event_id,primary"   json:"event_id"`       //
	CapType       uint        `orm:"cap_type,primary"   json:"cap_type"`       //
	ServerId      int         `orm:"server_id,primary"  json:"server_id"`      //
	MId           int         `orm:"m_id,primary"       json:"m_id"`           //
	StartTime     *gtime.Time `orm:"start_time,primary" json:"start_time"`     //
	EndTime       *gtime.Time `orm:"end_time"           json:"end_time"`       //
	HandicapValue int         `orm:"handicap_value"     json:"handicap_value"` //
}

// MemberInfo is the golang structure for table member_info.
type MemberInfo struct {
	MId          int         `orm:"m_id,primary"   json:"m_id"`           //
	UserId       string      `orm:"user_id"        json:"user_id"`        //
	UserName     string      `orm:"user_name"      json:"user_name"`      //
	FirstSsn     string      `orm:"first_ssn"      json:"first_ssn"`      //
	SecondSsn    string      `orm:"second_ssn"     json:"second_ssn"`     //
	Passwd       string      `orm:"passwd"         json:"passwd"`         //
	MobileNo     string      `orm:"mobile_no"      json:"mobile_no"`      //
	RegDate      int         `orm:"reg_date"       json:"reg_date"`       //
	Email        string      `orm:"email"          json:"email"`          //
	QNo          int         `orm:"q_no"           json:"q_no"`           //
	QAnswer      string      `orm:"q_answer"       json:"q_answer"`       //
	UpdtDate     *gtime.Time `orm:"updt_date"      json:"updt_date"`      //
	State        int         `orm:"state"          json:"state"`          //
	Nickname     string      `orm:"nickname"       json:"nickname"`       //
	EmailYn      string      `orm:"email_yn"       json:"email_yn"`       //
	SsnCheck     uint        `orm:"ssn_check"      json:"ssn_check"`      //
	Slot         uint        `orm:"slot"           json:"slot"`           //
	LastPlayTime *gtime.Time `orm:"last_play_time" json:"last_play_time"` //
	HangameFlag  int         `orm:"hangame_flag"   json:"hangame_flag"`   //
	HanmonFlag   int         `orm:"hanmon_flag"    json:"hanmon_flag"`    //
	MType        int         `orm:"m_type"         json:"m_type"`         //
}

// MemberInfoDetail is the golang structure for table member_info_detail.
type MemberInfoDetail struct {
	MId           int         `orm:"m_id,primary"   json:"m_id"`           //
	Zipcode       string      `orm:"zipcode"        json:"zipcode"`        //
	Address       string      `orm:"address"        json:"address"`        //
	AddressDetail string      `orm:"address_detail" json:"address_detail"` //
	OccDate       *gtime.Time `orm:"occ_date"       json:"occ_date"`       //
}

// MemberInfoEuckr is the golang structure for table member_info_euckr.
type MemberInfoEuckr struct {
	MId          int         `orm:"m_id,primary"   json:"m_id"`           //
	UserId       string      `orm:"user_id"        json:"user_id"`        //
	UserName     string      `orm:"user_name"      json:"user_name"`      //
	FirstSsn     string      `orm:"first_ssn"      json:"first_ssn"`      //
	SecondSsn    string      `orm:"second_ssn"     json:"second_ssn"`     //
	Passwd       string      `orm:"passwd"         json:"passwd"`         //
	MobileNo     string      `orm:"mobile_no"      json:"mobile_no"`      //
	RegDate      int         `orm:"reg_date"       json:"reg_date"`       //
	Email        string      `orm:"email"          json:"email"`          //
	QNo          int         `orm:"q_no"           json:"q_no"`           //
	QAnswer      string      `orm:"q_answer"       json:"q_answer"`       //
	UpdtDate     *gtime.Time `orm:"updt_date"      json:"updt_date"`      //
	State        int         `orm:"state"          json:"state"`          //
	Nickname     string      `orm:"nickname"       json:"nickname"`       //
	EmailYn      string      `orm:"email_yn"       json:"email_yn"`       //
	SsnCheck     uint        `orm:"ssn_check"      json:"ssn_check"`      //
	Slot         uint        `orm:"slot"           json:"slot"`           //
	LastPlayTime *gtime.Time `orm:"last_play_time" json:"last_play_time"` //
	HangameFlag  int         `orm:"hangame_flag"   json:"hangame_flag"`   //
}

// MemberInfoMileage is the golang structure for table member_info_mileage.
type MemberInfoMileage struct {
	MId          int         `orm:"m_id,primary"   json:"m_id"`           //
	UserId       string      `orm:"user_id"        json:"user_id"`        //
	UserName     string      `orm:"user_name"      json:"user_name"`      //
	FirstSsn     string      `orm:"first_ssn"      json:"first_ssn"`      //
	SecondSsn    string      `orm:"second_ssn"     json:"second_ssn"`     //
	Passwd       string      `orm:"passwd"         json:"passwd"`         //
	MobileNo     string      `orm:"mobile_no"      json:"mobile_no"`      //
	RegDate      int         `orm:"reg_date"       json:"reg_date"`       //
	Email        string      `orm:"email"          json:"email"`          //
	QNo          int         `orm:"q_no"           json:"q_no"`           //
	QAnswer      string      `orm:"q_answer"       json:"q_answer"`       //
	UpdtDate     *gtime.Time `orm:"updt_date"      json:"updt_date"`      //
	State        int         `orm:"state"          json:"state"`          //
	Nickname     string      `orm:"nickname"       json:"nickname"`       //
	EmailYn      string      `orm:"email_yn"       json:"email_yn"`       //
	SsnCheck     uint        `orm:"ssn_check"      json:"ssn_check"`      //
	Slot         uint        `orm:"slot"           json:"slot"`           //
	LastPlayTime *gtime.Time `orm:"last_play_time" json:"last_play_time"` //
	HangameFlag  int         `orm:"hangame_flag"   json:"hangame_flag"`   //
	HanmonFlag   int         `orm:"hanmon_flag"    json:"hanmon_flag"`    //
	Mileage      int         `orm:"mileage"        json:"mileage"`        //
}

// MemberInfoOld is the golang structure for table member_info_old.
type MemberInfoOld struct {
	MId          int         `orm:"m_id,primary"   json:"m_id"`           //
	UserId       string      `orm:"user_id"        json:"user_id"`        //
	UserName     string      `orm:"user_name"      json:"user_name"`      //
	FirstSsn     string      `orm:"first_ssn"      json:"first_ssn"`      //
	SecondSsn    string      `orm:"second_ssn"     json:"second_ssn"`     //
	Passwd       string      `orm:"passwd"         json:"passwd"`         //
	MobileNo     string      `orm:"mobile_no"      json:"mobile_no"`      //
	RegDate      int         `orm:"reg_date"       json:"reg_date"`       //
	Email        string      `orm:"email"          json:"email"`          //
	QNo          int         `orm:"q_no"           json:"q_no"`           //
	QAnswer      string      `orm:"q_answer"       json:"q_answer"`       //
	UpdtDate     *gtime.Time `orm:"updt_date"      json:"updt_date"`      //
	State        int         `orm:"state"          json:"state"`          //
	Nickname     string      `orm:"nickname"       json:"nickname"`       //
	EmailYn      string      `orm:"email_yn"       json:"email_yn"`       //
	SsnCheck     uint        `orm:"ssn_check"      json:"ssn_check"`      //
	LastPlayTime *gtime.Time `orm:"last_play_time" json:"last_play_time"` //
}

// MemberInfoUtf8 is the golang structure for table member_info_utf8.
type MemberInfoUtf8 struct {
	MId          int         `orm:"m_id,primary"   json:"m_id"`           //
	UserId       string      `orm:"user_id"        json:"user_id"`        //
	UserName     string      `orm:"user_name"      json:"user_name"`      //
	FirstSsn     string      `orm:"first_ssn"      json:"first_ssn"`      //
	SecondSsn    string      `orm:"second_ssn"     json:"second_ssn"`     //
	Passwd       string      `orm:"passwd"         json:"passwd"`         //
	MobileNo     string      `orm:"mobile_no"      json:"mobile_no"`      //
	RegDate      int         `orm:"reg_date"       json:"reg_date"`       //
	Email        string      `orm:"email"          json:"email"`          //
	QNo          int         `orm:"q_no"           json:"q_no"`           //
	QAnswer      string      `orm:"q_answer"       json:"q_answer"`       //
	UpdtDate     *gtime.Time `orm:"updt_date"      json:"updt_date"`      //
	State        int         `orm:"state"          json:"state"`          //
	Nickname     string      `orm:"nickname"       json:"nickname"`       //
	EmailYn      string      `orm:"email_yn"       json:"email_yn"`       //
	SsnCheck     uint        `orm:"ssn_check"      json:"ssn_check"`      //
	Slot         uint        `orm:"slot"           json:"slot"`           //
	LastPlayTime *gtime.Time `orm:"last_play_time" json:"last_play_time"` //
	HangameFlag  int         `orm:"hangame_flag"   json:"hangame_flag"`   //
	HanmonFlag   int         `orm:"hanmon_flag"    json:"hanmon_flag"`    //
}

// MemberJoinInfo is the golang structure for table member_join_info.
type MemberJoinInfo struct {
	MId            uint   `orm:"m_id,primary"     json:"m_id"`             //
	RegDate        int    `orm:"reg_date"         json:"reg_date"`         //
	Ip             string `orm:"ip"               json:"ip"`               //
	ContryCode     uint   `orm:"contry_code"      json:"contry_code"`      //
	LoginTime      int    `orm:"login_time"       json:"login_time"`       //
	ErrorType      uint   `orm:"error_type"       json:"error_type"`       //
	LoginIp        string `orm:"login_ip"         json:"login_ip"`         //
	GameUseHistory uint   `orm:"game_use_history" json:"game_use_history"` //
}

// MemberLioness is the golang structure for table member_lioness.
type MemberLioness struct {
	UserId string `orm:"user_id" json:"user_id"` //
}

// MemberMiles is the golang structure for table member_miles.
type MemberMiles struct {
	MId        int `orm:"m_id,primary" json:"m_id"`        //
	Miles      int `orm:"miles"        json:"miles"`       //
	DailyMiles int `orm:"daily_miles"  json:"daily_miles"` //
}

// MemberMouseSms is the golang structure for table member_mouse_sms.
type MemberMouseSms struct {
	MId     int         `orm:"m_id,primary" json:"m_id"`     //
	OccTime *gtime.Time `orm:"occ_time"     json:"occ_time"` //
	Cnt     uint        `orm:"cnt"          json:"cnt"`      //
}

// MemberPasswdMod is the golang structure for table member_passwd_mod.
type MemberPasswdMod struct {
	MId       int         `orm:"m_id,primary" json:"m_id"`       //
	FirstTime *gtime.Time `orm:"first_time"   json:"first_time"` //
	LastTime  *gtime.Time `orm:"last_time"    json:"last_time"`  //
	Cnt       uint        `orm:"cnt"          json:"cnt"`        //
}

// MemberPremiumHistory is the golang structure for table member_premium_history.
type MemberPremiumHistory struct {
	EventId      int         `orm:"event_id,primary"      json:"event_id"`      //
	PreType      uint        `orm:"pre_type,primary"      json:"pre_type"`      //
	MId          int         `orm:"m_id,primary"          json:"m_id"`          //
	ServiceStart *gtime.Time `orm:"service_start,primary" json:"service_start"` //
	ServiceEnd   *gtime.Time `orm:"service_end"           json:"service_end"`   //
}

// MemberPremiumNotuse is the golang structure for table member_premium_notuse.
type MemberPremiumNotuse struct {
	EventId      int         `orm:"event_id,primary"      json:"event_id"`      //
	PreType      uint        `orm:"pre_type,primary"      json:"pre_type"`      //
	MId          int         `orm:"m_id,primary"          json:"m_id"`          //
	ServiceStart *gtime.Time `orm:"service_start,primary" json:"service_start"` //
	ServiceEnd   *gtime.Time `orm:"service_end"           json:"service_end"`   //
	ServerId     uint        `orm:"server_id,primary"     json:"server_id"`     //
}

// MemberPunishHack is the golang structure for table member_punish_hack.
type MemberPunishHack struct {
	MId      uint   `orm:"m_id,primary" json:"m_id"`      //
	OccTime  uint   `orm:"occ_time"     json:"occ_time"`  //
	Period   uint   `orm:"period"       json:"period"`    //
	NowFlag  int    `orm:"now_flag"     json:"now_flag"`  //
	AutoFlag int    `orm:"auto_flag"    json:"auto_flag"` //
	Reason   string `orm:"reason"       json:"reason"`    //
	HackIp   string `orm:"hack_ip"      json:"hack_ip"`   //
}

// MemberPunishHackHistory is the golang structure for table member_punish_hack_history.
type MemberPunishHackHistory struct {
	MId      uint   `orm:"m_id"      json:"m_id"`      //
	OccTime  uint   `orm:"occ_time"  json:"occ_time"`  //
	Period   uint   `orm:"period"    json:"period"`    //
	NowFlag  int    `orm:"now_flag"  json:"now_flag"`  //
	AutoFlag int    `orm:"auto_flag" json:"auto_flag"` //
	Reason   string `orm:"reason"    json:"reason"`    //
}

// MemberPunishInfo is the golang structure for table member_punish_info.
type MemberPunishInfo struct {
	MId         int         `orm:"m_id,primary"        json:"m_id"`         //
	PunishType  int         `orm:"punish_type,primary" json:"punish_type"`  //
	OccTime     *gtime.Time `orm:"occ_time"            json:"occ_time"`     //
	PunishValue int         `orm:"punish_value"        json:"punish_value"` //
	ApplyFlag   int         `orm:"apply_flag"          json:"apply_flag"`   //
	StartTime   *gtime.Time `orm:"start_time"          json:"start_time"`   //
	EndTime     *gtime.Time `orm:"end_time"            json:"end_time"`     //
	AdminId     string      `orm:"admin_id"            json:"admin_id"`     //
	Reason      string      `orm:"reason"              json:"reason"`       //
}

// MemberPunishInfoHistory is the golang structure for table member_punish_info_history.
type MemberPunishInfoHistory struct {
	No          int         `orm:"no,primary"   json:"no"`           //
	MId         int         `orm:"m_id"         json:"m_id"`         //
	PunishType  int         `orm:"punish_type"  json:"punish_type"`  //
	OccTime     *gtime.Time `orm:"occ_time"     json:"occ_time"`     //
	PunishValue int         `orm:"punish_value" json:"punish_value"` //
	ApplyFlag   int         `orm:"apply_flag"   json:"apply_flag"`   //
	StartTime   *gtime.Time `orm:"start_time"   json:"start_time"`   //
	EndTime     *gtime.Time `orm:"end_time"     json:"end_time"`     //
	AdminId     string      `orm:"admin_id"     json:"admin_id"`     //
	Reason      string      `orm:"reason"       json:"reason"`       //
	IsKicked    int         `orm:"is_kicked"    json:"is_kicked"`    //
	FirstSsn    string      `orm:"first_ssn"    json:"first_ssn"`    //
	SecondSsn   string      `orm:"second_ssn"   json:"second_ssn"`   //
}

// MemberPunishInfoHistory2012 is the golang structure for table member_punish_info_history_2012.
type MemberPunishInfoHistory2012 struct {
	No          int         `orm:"no,primary"   json:"no"`           //
	MId         int         `orm:"m_id"         json:"m_id"`         //
	PunishType  int         `orm:"punish_type"  json:"punish_type"`  //
	OccTime     *gtime.Time `orm:"occ_time"     json:"occ_time"`     //
	PunishValue int         `orm:"punish_value" json:"punish_value"` //
	ApplyFlag   int         `orm:"apply_flag"   json:"apply_flag"`   //
	StartTime   *gtime.Time `orm:"start_time"   json:"start_time"`   //
	EndTime     *gtime.Time `orm:"end_time"     json:"end_time"`     //
	AdminId     string      `orm:"admin_id"     json:"admin_id"`     //
	Reason      string      `orm:"reason"       json:"reason"`       //
	IsKicked    int         `orm:"is_kicked"    json:"is_kicked"`    //
	FirstSsn    string      `orm:"first_ssn"    json:"first_ssn"`    //
	SecondSsn   string      `orm:"second_ssn"   json:"second_ssn"`   //
}

// MemberPunishInfoHistory2013 is the golang structure for table member_punish_info_history_2013.
type MemberPunishInfoHistory2013 struct {
	No          int         `orm:"no,primary"   json:"no"`           //
	MId         int         `orm:"m_id"         json:"m_id"`         //
	PunishType  int         `orm:"punish_type"  json:"punish_type"`  //
	OccTime     *gtime.Time `orm:"occ_time"     json:"occ_time"`     //
	PunishValue int         `orm:"punish_value" json:"punish_value"` //
	ApplyFlag   int         `orm:"apply_flag"   json:"apply_flag"`   //
	StartTime   *gtime.Time `orm:"start_time"   json:"start_time"`   //
	EndTime     *gtime.Time `orm:"end_time"     json:"end_time"`     //
	AdminId     string      `orm:"admin_id"     json:"admin_id"`     //
	Reason      string      `orm:"reason"       json:"reason"`       //
	IsKicked    int         `orm:"is_kicked"    json:"is_kicked"`    //
	FirstSsn    string      `orm:"first_ssn"    json:"first_ssn"`    //
	SecondSsn   string      `orm:"second_ssn"   json:"second_ssn"`   //
}

// MemberSafeEnsure is the golang structure for table member_safe_ensure.
type MemberSafeEnsure struct {
	MId         uint        `orm:"m_id"         json:"m_id"`         //
	OccTime     *gtime.Time `orm:"occ_time"     json:"occ_time"`     //
	MobileNo    string      `orm:"mobile_no"    json:"mobile_no"`    //
	ServiceFlag int         `orm:"service_flag" json:"service_flag"` //
	Type1Flag   int         `orm:"type1_flag"   json:"type_1_flag"`  //
	Type2Flag   int         `orm:"type2_flag"   json:"type_2_flag"`  //
	ExpireTime  *gtime.Time `orm:"expire_time"  json:"expire_time"`  //
	SettleId    string      `orm:"settle_id"    json:"settle_id"`    //
}

// MemberSafeEnsureHistory is the golang structure for table member_safe_ensure_history.
type MemberSafeEnsureHistory struct {
	ModFlag     int         `orm:"mod_flag"     json:"mod_flag"`     //
	ModTime     *gtime.Time `orm:"mod_time"     json:"mod_time"`     //
	MId         uint        `orm:"m_id"         json:"m_id"`         //
	OccTime     *gtime.Time `orm:"occ_time"     json:"occ_time"`     //
	MobileNo    string      `orm:"mobile_no"    json:"mobile_no"`    //
	ServiceFlag int         `orm:"service_flag" json:"service_flag"` //
	Type1Flag   int         `orm:"type1_flag"   json:"type_1_flag"`  //
	Type2Flag   int         `orm:"type2_flag"   json:"type_2_flag"`  //
	ExpireTime  *gtime.Time `orm:"expire_time"  json:"expire_time"`  //
	SettleId    string      `orm:"settle_id"    json:"settle_id"`    //
}

// MemberSecurityGrade is the golang structure for table member_security_grade.
type MemberSecurityGrade struct {
	MId                      int         `orm:"m_id,primary"                json:"m_id"`                        //
	LastVisitTime            *gtime.Time `orm:"last_visit_time"             json:"last_visit_time"`             //
	PassFailCnt              int         `orm:"pass_fail_cnt"               json:"pass_fail_cnt"`               //
	LastVaccineDate          *gtime.Time `orm:"last_vaccine_date"           json:"last_vaccine_date"`           //
	LastWindowDate           *gtime.Time `orm:"last_window_date"            json:"last_window_date"`            //
	GoblinPassMod            *gtime.Time `orm:"goblin_pass_mod"             json:"goblin_pass_mod"`             //
	GoblinFailCnt            int         `orm:"goblin_fail_cnt"             json:"goblin_fail_cnt"`             //
	SecurityCardReg          *gtime.Time `orm:"security_card_reg"           json:"security_card_reg"`           //
	SecurityCardFailCnt      int         `orm:"security_card_fail_cnt"      json:"security_card_fail_cnt"`      //
	MOptReg                  *gtime.Time `orm:"m_opt_reg"                   json:"m_opt_reg"`                   //
	PcOptReg                 *gtime.Time `orm:"pc_opt_reg"                  json:"pc_opt_reg"`                  //
	BlackIpTryTime           *gtime.Time `orm:"black_ip_try_time"           json:"black_ip_try_time"`           //
	LinearPassFailCnt        int         `orm:"linear_pass_fail_cnt"        json:"linear_pass_fail_cnt"`        //
	LastPassFailTime         uint        `orm:"last_pass_fail_time"         json:"last_pass_fail_time"`         //
	LastCheckTime            *gtime.Time `orm:"last_check_time"             json:"last_check_time"`             //
	PassModifyCheck          *gtime.Time `orm:"pass_modify_check"           json:"pass_modify_check"`           //
	MemberPcReg              *gtime.Time `orm:"member_pc_reg"               json:"member_pc_reg"`               //
	GatekeeperOtpReg         *gtime.Time `orm:"gatekeeper_otp_reg"          json:"gatekeeper_otp_reg"`          //
	GoblinValidityTime       int         `orm:"goblin_validity_time"        json:"goblin_validity_time"`        //
	SecurityCardValidityTime int         `orm:"security_card_validity_time" json:"security_card_validity_time"` //
	ValidityIp               string      `orm:"validity_ip"                 json:"validity_ip"`                 //
	CargopadStatus           int         `orm:"cargopad_status"             json:"cargopad_status"`             //
	CargopadMod              *gtime.Time `orm:"cargopad_mod"                json:"cargopad_mod"`                //
	CargopadValidityTime     int         `orm:"cargopad_validity_time"      json:"cargopad_validity_time"`      //
}

// MemberWhiteAccount is the golang structure for table member_white_account.
type MemberWhiteAccount struct {
	MId     uint        `orm:"m_id,primary" json:"m_id"`     //
	RegDate *gtime.Time `orm:"reg_date"     json:"reg_date"` //
}

// NewsBbs is the golang structure for table news_bbs.
type NewsBbs struct {
	BbsCode  int    `orm:"bbs_code,primary" json:"bbs_code"`  //
	EmphYn   int    `orm:"emph_yn,primary"  json:"emph_yn"`   //
	No       int    `orm:"no,primary"       json:"no"`        //
	UserId   string `orm:"user_id"          json:"user_id"`   //
	RegDate  int    `orm:"reg_date"         json:"reg_date"`  //
	HtmlYn   int    `orm:"html_yn"          json:"html_yn"`   //
	Subject  string `orm:"subject"          json:"subject"`   //
	Body     string `orm:"body"             json:"body"`      //
	Hits     int    `orm:"hits"             json:"hits"`      //
	PrevNo   int    `orm:"prev_no"          json:"prev_no"`   //
	NextNo   int    `orm:"next_no"          json:"next_no"`   //
	UpdtDate int    `orm:"updt_date"        json:"updt_date"` //
	UseYn    int    `orm:"use_yn"           json:"use_yn"`    //
	FileName string `orm:"file_name"        json:"file_name"` //
}

// Notice is the golang structure for table notice.
type Notice struct {
	BbsName     string  `orm:"bbs_name"     json:"bbs_name"`      //
	No          uint    `orm:"no"           json:"no"`            //
	Category    uint    `orm:"category"     json:"category"`      //
	MNickname   string  `orm:"m_nickname"   json:"m_nickname"`    //
	MId         uint    `orm:"m_id"         json:"m_id"`          //
	MUserId     string  `orm:"m_user_id"    json:"m_user_id"`     //
	MSex        string  `orm:"m_sex"        json:"m_sex"`         //
	Title       string  `orm:"title"        json:"title"`         //
	CreateDay   uint    `orm:"create_day"   json:"create_day"`    //
	Comment     uint    `orm:"comment"      json:"comment"`       //
	View        uint    `orm:"view"         json:"view"`          //
	Recom       uint    `orm:"recom"        json:"recom"`         //
	Adorn       uint    `orm:"adorn"        json:"adorn"`         //
	AdornColor1 uint    `orm:"adorn_color1" json:"adorn_color_1"` //
	AdornColor2 uint    `orm:"adorn_color2" json:"adorn_color_2"` //
	Depth       uint    `orm:"depth"        json:"depth"`         //
	Sequence    float64 `orm:"sequence"     json:"sequence"`      //
	Content     string  `orm:"content"      json:"content"`       //
	ContentType string  `orm:"content_type" json:"content_type"`  //
	Ip          string  `orm:"ip"           json:"ip"`            //
	Ring        uint    `orm:"ring"         json:"ring"`          //
	Sms         string  `orm:"sms"          json:"sms"`           //
}

// PasswdModEntry is the golang structure for table passwd_mod_entry.
type PasswdModEntry struct {
	MId       int         `orm:"m_id,primary"     json:"m_id"`       //
	OccTime   *gtime.Time `orm:"occ_time,primary" json:"occ_time"`   //
	Ip        string      `orm:"ip"               json:"ip"`         //
	PrePasswd string      `orm:"pre_passwd"       json:"pre_passwd"` //
}

// PswdQstion is the golang structure for table pswd_qstion.
type PswdQstion struct {
	QNo   int    `orm:"q_no,primary" json:"q_no"`   //
	QText string `orm:"q_text"       json:"q_text"` //
}

// PswdQstionDirect is the golang structure for table pswd_qstion_direct.
type PswdQstionDirect struct {
	MId   int    `orm:"m_id,primary" json:"m_id"`   //
	QText string `orm:"q_text"       json:"q_text"` //
}

// PuUserList is the golang structure for table pu_user_list.
type PuUserList struct {
	MId uint `orm:"m_id,primary" json:"m_id"` //
}

// SlangList is the golang structure for table slang_list.
type SlangList struct {
	Slang string `orm:"slang,primary" json:"slang"` //
}

// SlangListName is the golang structure for table slang_list_name.
type SlangListName struct {
	Slang string `orm:"slang,primary" json:"slang"` //
}

// Test is the golang structure for table test.
type Test struct {
	A int         `orm:"a" json:"a"` //
	B *gtime.Time `orm:"b" json:"b"` //
}

// Test2 is the golang structure for table test2.
type Test2 struct {
	A uint `orm:"a" json:"a"` //
}

// TmeCharac is the golang structure for table tme_charac.
type TmeCharac struct {
	MId               int         `orm:"m_id"                json:"m_id"`                //
	CharacNo          int         `orm:"charac_no"           json:"charac_no"`           //
	CharacName        string      `orm:"charac_name"         json:"charac_name"`         //
	Village           int         `orm:"village"             json:"village"`             //
	Job               int         `orm:"job"                 json:"job"`                 //
	Lev               int         `orm:"lev"                 json:"lev"`                 //
	Exp               int         `orm:"exp"                 json:"exp"`                 //
	GrowType          int         `orm:"grow_type"           json:"grow_type"`           //
	HP                uint        `orm:"HP"                  json:"hp"`                  //
	MaxHP             uint        `orm:"maxHP"               json:"max_hp"`              //
	MaxMP             uint        `orm:"maxMP"               json:"max_mp"`              //
	PhyAttack         uint        `orm:"phy_attack"          json:"phy_attack"`          //
	PhyDefense        uint        `orm:"phy_defense"         json:"phy_defense"`         //
	MagAttack         uint        `orm:"mag_attack"          json:"mag_attack"`          //
	MagDefense        uint        `orm:"mag_defense"         json:"mag_defense"`         //
	ElementResist     []byte      `orm:"element_resist"      json:"element_resist"`      //
	SpecProperty      []byte      `orm:"spec_property"       json:"spec_property"`       //
	InvenWeight       int         `orm:"inven_weight"        json:"inven_weight"`        //
	HpRegen           int         `orm:"hp_regen"            json:"hp_regen"`            //
	MpRegen           int         `orm:"mp_regen"            json:"mp_regen"`            //
	MoveSpeed         uint        `orm:"move_speed"          json:"move_speed"`          //
	AttackSpeed       uint        `orm:"attack_speed"        json:"attack_speed"`        //
	CastSpeed         uint        `orm:"cast_speed"          json:"cast_speed"`          //
	HitRecovery       int         `orm:"hit_recovery"        json:"hit_recovery"`        //
	Jump              int         `orm:"jump"                json:"jump"`                //
	CharacWeight      int         `orm:"charac_weight"       json:"charac_weight"`       //
	Fatigue           int         `orm:"fatigue"             json:"fatigue"`             //
	MaxFatigue        int         `orm:"max_fatigue"         json:"max_fatigue"`         //
	PremiumFatigue    int         `orm:"premium_fatigue"     json:"premium_fatigue"`     //
	MaxPremiumFatigue int         `orm:"max_premium_fatigue" json:"max_premium_fatigue"` //
	CreateTime        *gtime.Time `orm:"create_time"         json:"create_time"`         //
	LastPlayTime      *gtime.Time `orm:"last_play_time"      json:"last_play_time"`      //
	DungeonClearPoint int         `orm:"dungeon_clear_point" json:"dungeon_clear_point"` //
	DeleteTime        *gtime.Time `orm:"delete_time"         json:"delete_time"`         //
	DeleteFlag        int         `orm:"delete_flag"         json:"delete_flag"`         //
	GuildId           uint        `orm:"guild_id"            json:"guild_id"`            //
	GuildRight        int         `orm:"guild_right"         json:"guild_right"`         //
	MemberFlag        int         `orm:"member_flag"         json:"member_flag"`         //
}

// TmpCharac is the golang structure for table tmp_charac.
type TmpCharac struct {
	MId               int         `orm:"m_id"                json:"m_id"`                //
	CharacNo          int         `orm:"charac_no"           json:"charac_no"`           //
	CharacName        string      `orm:"charac_name"         json:"charac_name"`         //
	Village           int         `orm:"village"             json:"village"`             //
	Job               int         `orm:"job"                 json:"job"`                 //
	Lev               int         `orm:"lev"                 json:"lev"`                 //
	Exp               int         `orm:"exp"                 json:"exp"`                 //
	GrowType          int         `orm:"grow_type"           json:"grow_type"`           //
	HP                uint        `orm:"HP"                  json:"hp"`                  //
	MaxHP             uint        `orm:"maxHP"               json:"max_hp"`              //
	MaxMP             uint        `orm:"maxMP"               json:"max_mp"`              //
	PhyAttack         uint        `orm:"phy_attack"          json:"phy_attack"`          //
	PhyDefense        uint        `orm:"phy_defense"         json:"phy_defense"`         //
	MagAttack         uint        `orm:"mag_attack"          json:"mag_attack"`          //
	MagDefense        uint        `orm:"mag_defense"         json:"mag_defense"`         //
	ElementResist     []byte      `orm:"element_resist"      json:"element_resist"`      //
	SpecProperty      []byte      `orm:"spec_property"       json:"spec_property"`       //
	InvenWeight       int         `orm:"inven_weight"        json:"inven_weight"`        //
	HpRegen           int         `orm:"hp_regen"            json:"hp_regen"`            //
	MpRegen           int         `orm:"mp_regen"            json:"mp_regen"`            //
	MoveSpeed         uint        `orm:"move_speed"          json:"move_speed"`          //
	AttackSpeed       uint        `orm:"attack_speed"        json:"attack_speed"`        //
	CastSpeed         uint        `orm:"cast_speed"          json:"cast_speed"`          //
	HitRecovery       int         `orm:"hit_recovery"        json:"hit_recovery"`        //
	Jump              int         `orm:"jump"                json:"jump"`                //
	CharacWeight      int         `orm:"charac_weight"       json:"charac_weight"`       //
	Fatigue           int         `orm:"fatigue"             json:"fatigue"`             //
	MaxFatigue        int         `orm:"max_fatigue"         json:"max_fatigue"`         //
	PremiumFatigue    int         `orm:"premium_fatigue"     json:"premium_fatigue"`     //
	MaxPremiumFatigue int         `orm:"max_premium_fatigue" json:"max_premium_fatigue"` //
	CreateTime        *gtime.Time `orm:"create_time"         json:"create_time"`         //
	LastPlayTime      *gtime.Time `orm:"last_play_time"      json:"last_play_time"`      //
	DungeonClearPoint int         `orm:"dungeon_clear_point" json:"dungeon_clear_point"` //
	DeleteTime        *gtime.Time `orm:"delete_time"         json:"delete_time"`         //
	DeleteFlag        int         `orm:"delete_flag"         json:"delete_flag"`         //
	GuildId           uint        `orm:"guild_id"            json:"guild_id"`            //
	GuildRight        int         `orm:"guild_right"         json:"guild_right"`         //
	MemberFlag        int         `orm:"member_flag"         json:"member_flag"`         //
}

// UnderAgeConsent is the golang structure for table under_age_consent.
type UnderAgeConsent struct {
	MId               uint   `orm:"m_id"                json:"m_id"`                //
	ConsentType       uint   `orm:"consent_type"        json:"consent_type"`        //
	LimitMoney        uint   `orm:"limit_money"         json:"limit_money"`         //
	ParentName        string `orm:"parent_name"         json:"parent_name"`         //
	ParentJumin       uint64 `orm:"parent_jumin"        json:"parent_jumin"`        //
	ParentPhone1      uint   `orm:"parent_phone1"       json:"parent_phone_1"`      //
	ParentPhone2      uint   `orm:"parent_phone2"       json:"parent_phone_2"`      //
	ParentPhone3      uint   `orm:"parent_phone3"       json:"parent_phone_3"`      //
	ParentEmail       string `orm:"parent_email"        json:"parent_email"`        //
	ParentConsentType uint   `orm:"parent_consent_type" json:"parent_consent_type"` //
	NoticeType        uint   `orm:"notice_type"         json:"notice_type"`         //
	NoticeAddr        string `orm:"notice_addr"         json:"notice_addr"`         //
	CreateDate        uint   `orm:"create_date"         json:"create_date"`         //
	ConsentDate       uint   `orm:"consent_date"        json:"consent_date"`        //
	ConsentYn         uint   `orm:"consent_yn"          json:"consent_yn"`          //
	HistoryYn         uint   `orm:"history_yn"          json:"history_yn"`          //
}

// UnderBillingConfirm is the golang structure for table under_billing_confirm.
type UnderBillingConfirm struct {
	MId               uint   `orm:"m_id,primary"        json:"m_id"`                //
	ParentName        string `orm:"parent_name"         json:"parent_name"`         //
	ParentJumin       uint64 `orm:"parent_jumin"        json:"parent_jumin"`        //
	ParentPhone1      uint   `orm:"parent_phone1"       json:"parent_phone_1"`      //
	ParentPhone2      uint   `orm:"parent_phone2"       json:"parent_phone_2"`      //
	ParentPhone3      uint   `orm:"parent_phone3"       json:"parent_phone_3"`      //
	ParentEmail       string `orm:"parent_email"        json:"parent_email"`        //
	ParentConsentType uint   `orm:"parent_consent_type" json:"parent_consent_type"` //
	CreateDate        uint   `orm:"create_date"         json:"create_date"`         //
	ConsentDate       uint   `orm:"consent_date"        json:"consent_date"`        //
	ConsentYn         uint   `orm:"consent_yn"          json:"consent_yn"`          //
}

// UserBan is the golang structure for table user_ban.
type UserBan struct {
	No           uint   `orm:"no,primary"    json:"no"`            //
	Category     int    `orm:"category"      json:"category"`      //
	MId          uint   `orm:"m_id"          json:"m_id"`          //
	BanTerm      uint   `orm:"ban_term"      json:"ban_term"`      //
	BanReason    uint   `orm:"ban_reason"    json:"ban_reason"`    //
	DetailReason string `orm:"detail_reason" json:"detail_reason"` //
	BanDate      uint   `orm:"ban_date"      json:"ban_date"`      //
	CancelReason string `orm:"cancel_reason" json:"cancel_reason"` //
	CancelDate   uint   `orm:"cancel_date"   json:"cancel_date"`   //
	AdminId      uint   `orm:"admin_id"      json:"admin_id"`      //
	Status       uint   `orm:"status"        json:"status"`        //
	FirstSsn     string `orm:"first_ssn"     json:"first_ssn"`     //
	SecondSsn    string `orm:"second_ssn"    json:"second_ssn"`    //
}
