const JOB = [
    {
        label:"鬼剑士",
        value:0,
        color:'#4CAF50',
        text_color:'#ffffff',
        grow_type: {
            17:{
                label:"剑魂",
                value:17,
                color:'#C8E6C9',
            },
            18:{
                label:"鬼泣",
                value:18,
                color:'#81C784',
            },
            19:{
                label:"狂战士",
                value:19,
                color:'#43A047',
            },
            20:{
                label:"阿修罗",
                value:20,
                color:'#1B5E20',
                text_color:'#ffffff',
            },
        },
    },
    {
        label:"女格斗",
        value:1,
        color:'#E91E63',
        grow_type: {
            17:{
                label:"气功师",
                value:17,
                color:'#FCE4EC',
            },
            18:{
                label:"散打",
                value:18,
                color:'#F48FB1',
            },
            19:{
                label:"街霸",
                value:19,
                color:'#F06292',
            },
            20:{
                label:"柔道",
                value:20,
                color:'#AD1457',
            },
        },
    },
    {
        label:"男枪手",
        value:2,
        color:'#9C27B0',
        grow_type: {
            17:{
                label:"漫游枪手",
                value:17,
                color:'#F3E5F5',
            },
            18:{
                label:"枪炮师",
                value:18,
                color:'#CE93D8',
            },
            19:{
                label:"机械师",
                value:19,
                color:'#AB47BC',
            },
            20:{
                label:"弹药专家",
                value:20,
                color:'#6A1B9A',
            },
        },
    },
    {
        label:"女法师",
        value:3,
        color:'#3F51B5',
        grow_type: {
            17:{
                label:"元素师",
                value:17,
                color:'#E8EAF6',
            },
            18:{
                label:"召唤师",
                value:18,
                color:'#C5CAE9',
            },
            19:{
                label:"战斗法师",
                value:19,
                color:'#7986CB',
            },
            20:{
                label:"魔道学者",
                value:20,
                color:'#283593',
            },
        },
    },
    {
        label:"圣职者",
        value:4,
        color:'#009688',
        grow_type: {
            17:{
                label:"圣骑士",
                value:17,
                color:'#E0F2F1',
            },
            18:{
                label:"蓝拳圣使",
                value:18,
                color:'#80CBC4',
            },
            19:{
                label:"驱魔师",
                value:19,
                color:'#26A69A',
            },
            20:{
                label:"复仇者",
                value:20,
                color:'#00796B',
            },
        },
    },
    {
        label:"女枪手",
        value:5,
        color:'#CDDC39',
        grow_type: {
            17:{
                label:"漫游枪手",
                value:17,
                color:'#F0F4C3',
            },
            18:{
                label:"枪炮师",
                value:18,
                color:'#DCE775',
            },
            19:{
                label:"机械师",
                value:19,
                color:'#C0CA33',
            },
            20:{
                label:"弹药专家",
                value:20,
                color:'#9E9D24',
            },
        },
    },
    {
        label:"灵魂收割者",
        value:6,
        color:'#FF9800',
        grow_type: {
            17:{
                label:"刺客",
                value:17,
                color:'#FFCC80',
            },
            18:{
                label:"死灵术士",
                value:18,
                color:'#FFA726',
            },
        },
    },
    {
        label:"男格斗",
        value:7,
        color:'#795548',
        grow_type: {
            17:{
                label:"气功师",
                value:17,
                color:'#D7CCC8',
            },
            18:{
                label:"散打",
                value:18,
                color:'#A1887F',
            },
            19:{
                label:"街霸",
                value:19,
                color:'#5D4037',
            },
            20:{
                label:"柔道",
                value:20,
                color:'#4E342E',
                text_color:'#ffffff',
            },
        },
    },
    {
        label:"男法师",
        value:8,
        color:'#607D8B',
        grow_type: {
            17:{
                label:"元素爆破",
                value:17,
                color:'#CFD8DC',
            },
            18:{
                label:"冰洁师",
                value:18,
                color:'#90A4AE',
            },
        },
    },
    {
        label:"暗黑骑士",
        value:9,
        color:'#263238',
        grow_type: {
            0:{
                label:"暗黑骑士",
                value:0,
                color:'#263238',
                text_color:'#ffffff',
            },
        },
    },
];
export {
    JOB,
}